In [ ]:
# import libraries
# Import necessary libraries
import pandas as pd
import numpy as np
import unidecode

In [2]:
# load all files
df_standard = pd.read_csv('FBref_datasets/top5_league_stats.csv')
df_shooting = pd.read_csv('FBref_datasets/top5_league_shooting.csv')
df_passing = pd.read_csv('FBref_datasets/top5_league_passing.csv')
df_pass_type = pd.read_csv('FBref_datasets/top5_league_passing_types.csv')
df_shot_creation = pd.read_csv('FBref_datasets/top5_league_gca.csv')
df_defense = pd.read_csv('FBref_datasets/top5_league_defense.csv')
df_possession = pd.read_csv('FBref_datasets/top5_league_possession.csv')
df_misc = pd.read_csv('FBref_datasets/top5_league_misc.csv')
df_playing_time = pd.read_csv('FBref_datasets/top5_league_playingtime.csv')

# df_standard

In [3]:
# RK - s.no, matches -> matches 
def clean_data(df):
    df = df.drop(columns=['Rk', 'Matches'])
    return df

In [4]:
# apply the clean data to each of data frame
df_standard = clean_data(df_standard)
df_shooting = clean_data(df_shooting)
df_passing = clean_data(df_passing)
df_pass_type = clean_data(df_pass_type)
df_shot_creation = clean_data(df_shot_creation)
df_defense = clean_data(df_defense)
df_possession = clean_data(df_possession)
df_misc = clean_data(df_misc)
df_playing_time = clean_data(df_playing_time)

df_standard

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,25-026,2000.0,3,1,86,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,Max Aarons,eng ENG,MF,Valencia,es La Liga,25-026,2000.0,1,0,31,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-263,2003.0,1,1,65,...,0.00,0.00,0.00,0.00,0.00,0.10,0.00,0.10,0.10,0.10
3,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,21-014,2004.0,6,0,88,...,0.00,0.00,0.00,0.00,0.00,0.06,0.00,0.06,0.06,0.06
4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-300,2006.0,1,0,3,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2533,Martín Zubimendi,es ESP,MF,Real Sociedad,es La Liga,25-363,1999.0,20,19,1714,...,0.05,0.05,0.11,0.05,0.11,0.08,0.04,0.12,0.08,0.12
2534,Szymon Żurkowski,pl POL,MF,Empoli,it Serie A,27-127,1997.0,1,0,8,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2535,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,26-044,1998.0,15,14,1200,...,0.07,0.23,0.30,0.00,0.23,0.22,0.18,0.40,0.16,0.34
2536,Milan Đurić,ba BIH,FW,Monza,it Serie A,34-253,1990.0,18,13,1270,...,0.28,0.07,0.35,0.28,0.35,0.21,0.08,0.28,0.21,0.28
2537,Milan Đurić,ba BIH,FW,Parma,it Serie A,34-253,1990.0,1,1,69,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [5]:
# Function to remove duplicates of players who transfered mid season
def remove_duplicates(df):
    df = df.sort_values('Min', ascending=False).drop_duplicates(subset=['Player', 'Age'], keep='first').reset_index(drop=True)
    return df

In [6]:
# combining all files into one
from functools import reduce

data_frames = [
    df_standard,
    df_shooting,
    df_passing,
    df_pass_type,
    df_shot_creation,
    df_defense,
    df_possession,
    df_misc,
    df_playing_time
]

merge_keys = [
    'Player', 'Nation', 'Pos', 'Squad',
    'Comp', 'Age', 'Born'
]

combined_df = data_frames[0].copy()

for df_temp in data_frames[1:]:
    duplicate_columns = [
        col for col in df_temp.columns
        if col in combined_df.columns and col not in merge_keys
    ]

    df_temp = df_temp.drop(columns=duplicate_columns)

    combined_df = pd.merge(
        combined_df,
        df_temp,
        on=merge_keys,
        how='left'
    )


combined_df = remove_duplicates(combined_df)
combined_df

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,On-Off.1
0,David Raya,es ESP,GK,Arsenal,eng Premier League,29-137,1995.0,23,23,2070,...,44.0,21.0,23.0,1.00,NaN,37.6,20.4,17.2,0.75,NaN
1,Antonee Robinson,us USA,DF,Fulham,eng Premier League,27-175,1997.0,23,23,2070,...,34.0,31.0,3.0,0.13,NaN,32.4,26.8,5.5,0.24,NaN
2,André Onana,cm CMR,GK,Manchester Utd,eng Premier League,28-303,1996.0,23,23,2070,...,28.0,32.0,-4.0,-0.17,NaN,32.8,33.9,-1.1,-0.05,NaN
3,Matz Sels,be BEL,GK,Nott'ham Forest,eng Premier League,32-339,1992.0,23,23,2070,...,33.0,27.0,6.0,0.26,NaN,28.5,25.8,2.7,0.12,NaN
4,Nathan Collins,ie IRL,DF,Brentford,eng Premier League,23-275,2001.0,23,23,2070,...,42.0,40.0,2.0,0.09,NaN,36.4,38.6,-2.1,-0.09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2469,Faik Sakar,de GER,MF,RB Leipzig,de Bundesliga,17-016,2008.0,1,0,1,...,0.0,0.0,0.0,0.00,-0.26,0.0,0.0,0.0,0.00,0.24
2470,Yoann Cissé,fr FRA,MF,Auxerre,fr Ligue 1,20-048,2004.0,1,0,1,...,0.0,0.0,0.0,0.00,0.21,0.4,0.1,0.3,26.77,27.38
2471,Alfie Pond,eng ENG,DF,Wolves,eng Premier League,20-335,2004.0,1,0,1,...,0.0,0.0,0.0,0.00,0.87,0.0,0.0,0.0,0.00,0.65
2472,Will Alves,eng ENG,FW,Leicester City,eng Premier League,19-362,2005.0,1,0,1,...,0.0,0.0,0.0,0.00,1.04,0.0,0.0,0.0,2.92,3.84
2473,Diego Gómez,py PAR,MF,Brighton,eng Premier League,21-309,2003.0,1,0,1,...,0.0,0.0,0.0,0.00,-0.17,0.0,0.0,0.0,0.00,0.07

In [7]:
combined_df.rename(columns={"Squad": "Team"}, inplace=True)

In [ ]:
#removing all goalkeepres from dataset
combined_df.drop(combined_df[combined_df.Pos == 'GK'].index, inplace=True)

# fixing index + removing all who hasnt even played for 90 minutes
#! might change later
combined_df.drop(combined_df[combined_df.Min < 90].index, inplace=True)
combined_df.reset_index(drop=True, inplace=True)

combined_df

,Player,Nation,Pos,Team,Comp,Age,Born,MP,Starts,Min,...,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,On-Off.1
0,Antonee Robinson,us USA,DF,Fulham,eng Premier League,27-175,1997.0,23,23,2070,...,34.0,31.0,3.0,0.13,NaN,32.4,26.8,5.5,0.24,NaN
1,Nathan Collins,ie IRL,DF,Brentford,eng Premier League,23-275,2001.0,23,23,2070,...,42.0,40.0,2.0,0.09,NaN,36.4,38.6,-2.1,-0.09,NaN
2,Illia Zabarnyi,ua UKR,DF,Bournemouth,eng Premier League,22-151,2002.0,23,23,2070,...,41.0,26.0,15.0,0.65,NaN,44.0,28.7,15.3,0.67,NaN
3,Bryan Mbeumo,cm CMR,FW,Brentford,eng Premier League,25-176,1999.0,23,23,2064,...,42.0,38.0,4.0,0.17,30.17,35.9,37.8,-1.9,-0.08,4.21
4,Moisés Caicedo,ec ECU,MF,Chelsea,eng Premier League,23-089,2001.0,23,23,2035,...,43.0,29.0,14.0,0.62,-1.95,46.4,31.8,14.6,0.64,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,Enzo Ebosse,cm CMR,DF,Udinese,it Serie A,25-325,1999.0,2,0,90,...,0.0,1.0,-1.0,-1.00,-0.62,0.6,0.7,-0.1,-0.13,0.38
1985,Ronald Araújo,uy URU,DF,Barcelona,es La Liga,25-329,1999.0,1,1,90,...,1.0,1.0,0.0,0.00,-1.75,2.3,1.3,1.0,1.05,-0.30
1986,Roman Dixon,eng ENG,DF,Everton,eng Premier League,20-035,2004.0,1,1,90,...,0.0,4.0,-4.0,-4.00,-3.76,1.0,2.4,-1.5,-1.45,-1.15
1987,Chadi Riad,ma MAR,DF,Crystal Palace,eng Premier League,21-227,2003.0,1,1,90,...,0.0,2.0,-2.0,-2.00,-1.91,1.3,1.4,0.0,-0.01,-0.01
1988,Fali Candé,gw GNB,DF,Venezia,it Serie A,27-006,1998.0,1,1,90,...,1.0,1.0,0.0,0.00,0.71,0.6,1.6,-1.1,-1.05,-0.36

In [9]:
players_with_missing_age_nation = combined_df.loc[
    combined_df[['Nation', 'Age', 'Born']].isna().any(axis=1),
    ['Player', 'Nation', 'Age', 'Born']
]

# only two players with missing age and nation so adding that info ourself

combined_df.loc[combined_df['Player'] == 'Atakan Karazor', 'Nation'] = 'ma MAR'

combined_df.loc[combined_df['Player'] == 'Max Moerstedt', 'Nation'] = 'de DEU'
combined_df.loc[combined_df['Player'] == 'Max Moerstedt', 'Age'] = '17-100'
combined_df.loc[combined_df['Player'] == 'Max Moerstedt', 'Born'] = 2006.0

In [10]:
defensive_columns = [
    'Tkl%', 'TklW', 'Tkl', 'Tkl+Int',
    'Blocks', 'Int', 'Clr', 'Err', 'Won%'
]

# Keep only columns that exist in combined_df
defensive_columns = [
    col for col in defensive_columns
    if col in combined_df.columns
]

print("Defensive columns found:", defensive_columns)

for col in defensive_columns:
    missing_players = combined_df[combined_df[col].isna()]

    print(f"\n{col} — Missing values by position:")
    print(missing_players['Pos'].value_counts())

Defensive columns found: ['Tkl%', 'TklW', 'Tkl', 'Tkl+Int', 'Blocks', 'Int', 'Clr', 'Err', 'Won%']

Tkl% — Missing values by position:
Pos
FW       13
DF        6
FW,MF     5
MF,FW     3
MF        2
MF,DF     1
DF,FW     1
DF,MF     1
FW,DF     1
Name: count, dtype: int64

TklW — Missing values by position:
Series([], Name: count, dtype: int64)

Tkl — Missing values by position:
Series([], Name: count, dtype: int64)

Tkl+Int — Missing values by position:
Series([], Name: count, dtype: int64)

Blocks — Missing values by position:
Series([], Name: count, dtype: int64)

Int — Missing values by position:
Series([], Name: count, dtype: int64)

Clr — Missing values by position:
Series([], Name: count, dtype: int64)

Err — Missing values by position:
Series([], Name: count, dtype: int64)

Won% — Missing values by position:
Pos
DF       4
MF,FW    3
MF       2
DF,FW    1
FW,MF    1
MF,DF    1
DF,MF    1
Name: count, dtype: int64

In [11]:
#? dealing with nulls 
# tkl% and won% -> if forward then set to 0 if defender then take mean

def fill_defensive_nulls(df):
    df = df.copy()

    defensive_percent_cols = ['Tkl%', 'Won%']

    for col in defensive_percent_cols:
        if col in df.columns:
            # Mean among players whose position includes DF
            defender_mean = df.loc[
                df['Pos'].str.contains('DF', na=False) &
                df[col].notna(),
                col
            ].mean()

            # Non-defenders: missing defensive percentage = 0
            non_defender_mask = (
                ~df['Pos'].str.contains('DF', na=False) &
                df[col].isna()
            )
            df.loc[non_defender_mask, col] = 0

            # Defenders: missing value = defender-specific mean
            defender_mask = (
                df['Pos'].str.contains('DF', na=False) &
                df[col].isna()
            )
            df.loc[defender_mask, col] = round(defender_mean, 1)

    return df

In [12]:
# to be replaced with mean as these are defenders stats and mostly defenders are missing it so to take better measure 
mean_columns = ['Succ%', 'Tkl%', 'Tkld%', 'Cmp%.3']

for col in mean_columns:
    combined_df[col] = combined_df[col].fillna(
        round(combined_df[col].mean(), 1)
    )
 
# Fill missing shot-related statistics with 0 -> since these belong to mostly defenders
zero_columns = ['SoT%', 'G/Sh', 'G/SoT', 'Dist', 'npxG/Sh', 'Mn/Start', 'Mn/Sub', 'On-Off', 'On-Off.1']

for col in zero_columns:
    combined_df[col] = combined_df[col].fillna(0)
    

# missing values after chages
combined_df[mean_columns + zero_columns].isnull().sum()

Succ%       0
Tkl%        0
Tkld%       0
Cmp%.3      0
SoT%        0
G/Sh        0
G/SoT       0
Dist        0
npxG/Sh     0
Mn/Start    0
Mn/Sub      0
On-Off      0
On-Off.1    0
dtype: int64

In [ ]:
# Load the transfer market dataset
tm_df = pd.read_csv('Transfermarkt _Datasets/top5_league_market_values.csv')
tm_df.drop(labels=tm_df.columns[0], axis=1, inplace=True)
tm_df.rename(columns={"Players": "Player"}, inplace=True)

# converting players name that contain letters such as ē,ā etc to ASCII equivalent
def clean_text(df, columns):
    for column in columns:
        df[column].fillna('', inplace=True)
        if column == 'Team':
             df[column] = df[column].apply(lambda x: unidecode.unidecode(x).lower())
        else:
           df[column] = df[column].apply(lambda x: unidecode.unidecode(x))
    return df

# Apply the cleaning function to both DataFrames
tm_df = clean_text(tm_df,['Player','Team'])
combined_df = clean_text(combined_df,['Player','Team'])

tm_df

C:\Users\gaura\AppData\Local\Temp\ipykernel_23164\3114444879.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna('', inplace=True)
C:\Users\gaura\AppData\Local\Temp\ipykernel_23164\3114444879.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna('', inplace=True)
C:\Users\gaura\AppData\Local\Temp\ipykernel_23164\3114444879.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna('', inplace=True)
C:\Users\gaura\AppData\Local\Temp\ipykernel_23164\3114444879.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna('', inplace=True)

                   Player      Values              Team
0              David Raya  40000000.0        arsenal fc
1                    Neto   2000000.0        arsenal fc
2          William Saliba  80000000.0        arsenal fc
3            Jakub Kiwior  28000000.0        arsenal fc
4      Riccardo Calafiori  45000000.0        arsenal fc
...                   ...         ...               ...
2472  Zuriko Davitashvili   8000000.0  as saint etienne
2473       Mathieu Cafaro   2000000.0  as saint etienne
2474        Lucas Stassin   5000000.0  as saint etienne
2475      Ibrahim Sissoko   2500000.0  as saint etienne
2476       Ibrahima Wadji    800000.0  as saint etienne

[2477 rows x 3 columns]

In [ ]:
# Change/clean the team names so they match in both datasets

replace_dict = {
    "arsenal fc": "arsenal",
    "aston villa": "aston villa",
    "afc bournemouth": "bournemouth",
    "brentford fc": "brentford",
    "brighton amp hove albion": "brighton",
    "fc chelsea": "chelsea",
    "crystal palace": "crystal palace",
    "fc everton": "everton",
    "fc fulham": "fulham",
    "ipswich town": "ipswich town",
    "leicester city": "leicester city",
    "fc liverpool": "liverpool",
    "manchester city": "manchester city",
    "manchester united": "manchester utd",
    "newcastle united": "newcastle utd",
    "nottingham forest": "nott'ham forest",
    "fc southampton": "southampton",
    "tottenham hotspur": "tottenham",
    "west ham united": "west ham",
    "wolverhampton wanderers": "wolves",
    "atletico madrid": "atletico madrid",
    "fc barcelona": "barcelona",
    "real madrid": "real madrid",
    "real betis sevilla": "betis",
    "fc sevilla": "sevilla",
    "ca osasuna": "osasuna",
    "real sociedad san sebastian": "real sociedad",
    "athletic bilbao": "athletic club",
    "deportivo alaves": "alaves",
    "celta vigo": "celta vigo",
     "fc valencia": "valencia",
    "fc villarreal": "villarreal",
     "fc getafe": "getafe",
    "rayo vallecano": "rayo vallecano",
     "rcd mallorca": "mallorca",
    "ud las palmas": "las palmas",
    "fc girona": "girona",
     "real valladolid": "valladolid",
     "cd leganes": "leganes",
     "espanyol barcelona": "espanyol",
     "inter milan": "inter",
    "ac mailand": "milan",
     "juventus turin": "juventus",
     "atalanta bergamo": "atalanta",
    "fc bologna": "bologna",
     "as rom": "roma",
    "lazio rom": "lazio",
     "ac florenz": "fiorentina",
    "fc turin": "torino",
    "ssc neapel": "napoli",
     "genua cfc": "genoa",
    "ac monza": "monza",
     "hellas verona": "hellas verona",
     "us lecce": "lecce",
     "udinese calcio": "udinese",
    "cagliari calcio": "cagliari",
     "fc empoli": "empoli",
    "parma calcio 1913": "parma",
     "como 1907": "como",
     "venezia fc": "venezia",
     "bayer 04 leverkusen": "leverkusen",
    "vfb stuttgart": "stuttgart",
    "fc bayern munchen": "bayern munich",
    "rasenballsport leipzig": "rb leipzig",
     "borussia dortmund": "dortmund",
    "eintracht frankfurt": "eint frankfurt",
     "tsg 1899 hoffenheim": "hoffenheim",
    "1 fc heidenheim 1846": "heidenheim",
    "sv werder bremen": "werder bremen",
    "sc freiburg": "freiburg",
     "fc augsburg": "augsburg",
    "vfl wolfsburg": "wolfsburg",
     "1 fsv mainz 05": "mainz 05",
    "borussia monchengladbach": "gladbach",
     "1 fc union berlin": "union berlin",
    "vfl bochum": "bochum",
    "fc st pauli": "st. pauli",
    "holstein kiel": "holstein kiel",
     "fc paris saint germain": "paris s-g",
    "as monaco": "monaco",
    "stade brest 29": "brest",
    "losc lille": "lille",
     "ogc nizza": "nice",
    "olympique lyon": "lyon",
    "rc lens": "lens",
     "olympique marseille": "marseille",
    "stade reims": "reims",
     "fc stade rennes": "rennes",
    "fc toulouse": "toulouse",
    "montpellier hsc": "montpellier",
    "rc strassburg alsace": "strasbourg",
    "fc nantes": "nantes",
    "ac le havre": "le havre",
     "aj auxerre": "auxerre",
    "sco angers":"angers",
    "as saint etienne":"saint-etienne",
}

tm_df.replace(replace_dict, inplace=True)

                   Player      Values           Team
0              David Raya  40000000.0        arsenal
1                    Neto   2000000.0        arsenal
2          William Saliba  80000000.0        arsenal
3            Jakub Kiwior  28000000.0        arsenal
4      Riccardo Calafiori  45000000.0        arsenal
...                   ...         ...            ...
2472  Zuriko Davitashvili   8000000.0  saint-etienne
2473       Mathieu Cafaro   2000000.0  saint-etienne
2474        Lucas Stassin   5000000.0  saint-etienne
2475      Ibrahim Sissoko   2500000.0  saint-etienne
2476       Ibrahima Wadji    800000.0  saint-etienne

[2477 rows x 3 columns]

In [15]:
combined_df

,Player,Nation,Pos,Team,Comp,Age,Born,MP,Starts,Min,...,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,On-Off.1
0,Antonee Robinson,us USA,DF,fulham,eng Premier League,27-175,1997.0,23,23,2070,...,34.0,31.0,3.0,0.13,0.00,32.4,26.8,5.5,0.24,0.00
1,Nathan Collins,ie IRL,DF,brentford,eng Premier League,23-275,2001.0,23,23,2070,...,42.0,40.0,2.0,0.09,0.00,36.4,38.6,-2.1,-0.09,0.00
2,Illia Zabarnyi,ua UKR,DF,bournemouth,eng Premier League,22-151,2002.0,23,23,2070,...,41.0,26.0,15.0,0.65,0.00,44.0,28.7,15.3,0.67,0.00
3,Bryan Mbeumo,cm CMR,FW,brentford,eng Premier League,25-176,1999.0,23,23,2064,...,42.0,38.0,4.0,0.17,30.17,35.9,37.8,-1.9,-0.08,4.21
4,Moises Caicedo,ec ECU,MF,chelsea,eng Premier League,23-089,2001.0,23,23,2035,...,43.0,29.0,14.0,0.62,-1.95,46.4,31.8,14.6,0.64,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,Enzo Ebosse,cm CMR,DF,udinese,it Serie A,25-325,1999.0,2,0,90,...,0.0,1.0,-1.0,-1.00,-0.62,0.6,0.7,-0.1,-0.13,0.38
1985,Ronald Araujo,uy URU,DF,barcelona,es La Liga,25-329,1999.0,1,1,90,...,1.0,1.0,0.0,0.00,-1.75,2.3,1.3,1.0,1.05,-0.30
1986,Roman Dixon,eng ENG,DF,everton,eng Premier League,20-035,2004.0,1,1,90,...,0.0,4.0,-4.0,-4.00,-3.76,1.0,2.4,-1.5,-1.45,-1.15
1987,Chadi Riad,ma MAR,DF,crystal palace,eng Premier League,21-227,2003.0,1,1,90,...,0.0,2.0,-2.0,-2.00,-1.91,1.3,1.4,0.0,-0.01,-0.01
1988,Fali Cande,gw GNB,DF,venezia,it Serie A,27-006,1998.0,1,1,90,...,1.0,1.0,0.0,0.00,0.71,0.6,1.6,-1.1,-1.05,-0.36

In [17]:
# displaying teamwise data
team_name = "chelsea"
result = tm_df.loc[tm_df['Team'] == team_name]

display(result)

                    Player       Values     Team
126         Robert Sanchez   20000000.0  chelsea
127        Filip Jorgensen   20000000.0  chelsea
128      Marcus Bettinelli     800000.0  chelsea
129        Lucas Bergstrom     700000.0  chelsea
130           Levi Colwill   55000000.0  chelsea
131            Axel Disasi   30000000.0  chelsea
132          Wesley Fofana   30000000.0  chelsea
133      Benoit Badiashile   28000000.0  chelsea
134       Tosin Adarabioyo   20000000.0  chelsea
136        Aaron Anselmino    8000000.0  chelsea
137         Marc Cucurella   30000000.0  chelsea
138           Ben Chilwell   20000000.0  chelsea
139           Renato Veiga   10000000.0  chelsea
140             Malo Gusto   35000000.0  chelsea
141            Reece James   30000000.0  chelsea
142      Joshua Acheampong    1000000.0  chelsea
143         Moises Caicedo   80000000.0  chelsea
144            Romeo Lavia   40000000.0  chelsea
145         Enzo Fernandez   75000000.0  chelsea
146  Kiernan Dewsbury-Hall   28000000.0  chelsea
147     Carney Chukwuemeka   15000000.0  chelsea
148         Cesare Casadei   10000000.0  chelsea
149            Cole Palmer  130000000.0  chelsea
150        Mykhailo Mudryk   30000000.0  chelsea
151           Jadon Sancho   30000000.0  chelsea
152             Pedro Neto   55000000.0  chelsea
153           Noni Madueke   40000000.0  chelsea
154             Joao Felix   30000000.0  chelsea
155        Nicolas Jackson   55000000.0  chelsea
156              Marc Guiu    8000000.0  chelsea

In [18]:
# MERGING the market value dataset with the stat dataset
final_df = combined_df.merge(
    tm_df,
    left_on=['Player', 'Team'],
    right_on=['Player', 'Team'],
    how='left'
)

final_df

,Player,Nation,Pos,Team,Comp,Age,Born,MP,Starts,Min,...,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,On-Off.1,Values
0,Antonee Robinson,us USA,DF,fulham,eng Premier League,27-175,1997.0,23,23,2070,...,31.0,3.0,0.13,0.00,32.4,26.8,5.5,0.24,0.00,28000000.0
1,Nathan Collins,ie IRL,DF,brentford,eng Premier League,23-275,2001.0,23,23,2070,...,40.0,2.0,0.09,0.00,36.4,38.6,-2.1,-0.09,0.00,28000000.0
2,Illia Zabarnyi,ua UKR,DF,bournemouth,eng Premier League,22-151,2002.0,23,23,2070,...,26.0,15.0,0.65,0.00,44.0,28.7,15.3,0.67,0.00,38000000.0
3,Bryan Mbeumo,cm CMR,FW,brentford,eng Premier League,25-176,1999.0,23,23,2064,...,38.0,4.0,0.17,30.17,35.9,37.8,-1.9,-0.08,4.21,50000000.0
4,Moises Caicedo,ec ECU,MF,chelsea,eng Premier League,23-089,2001.0,23,23,2035,...,29.0,14.0,0.62,-1.95,46.4,31.8,14.6,0.64,2.08,80000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,Enzo Ebosse,cm CMR,DF,udinese,it Serie A,25-325,1999.0,2,0,90,...,1.0,-1.0,-1.00,-0.62,0.6,0.7,-0.1,-0.13,0.38,2000000.0
1985,Ronald Araujo,uy URU,DF,barcelona,es La Liga,25-329,1999.0,1,1,90,...,1.0,0.0,0.00,-1.75,2.3,1.3,1.0,1.05,-0.30,55000000.0
1986,Roman Dixon,eng ENG,DF,everton,eng Premier League,20-035,2004.0,1,1,90,...,4.0,-4.0,-4.00,-3.76,1.0,2.4,-1.5,-1.45,-1.15,NaN
1987,Chadi Riad,ma MAR,DF,crystal palace,eng Premier League,21-227,2003.0,1,1,90,...,2.0,-2.0,-2.00,-1.91,1.3,1.4,0.0,-0.01,-0.01,15000000.0
1988,Fali Cande,gw GNB,DF,venezia,it Serie A,27-006,1998.0,1,1,90,...,1.0,0.0,0.00,0.71,0.6,1.6,-1.1,-1.05,-0.36,1500000.0

In [3]:
# filling the missing market value to mean of market values
final_df['Values'] = final_df['Values'].fillna((final_df['Values'].mean()/1000000).round()*1000000)
final_df

NameError: name 'final_df' is not defined

In [2]:
# selecting the valid subset of features to final data frame
selected_columns = [
    'Player', 'Pos', 'Team', 'Comp', 'Age', 'MP', 'Min', 'Gls', 'Ast',
    'G+A', 'xG', 'xA', 'SoT%', 'npxG/Sh', 'G-xG', 'Cmp%', 'TB',
     'Sw', 'Crs', 'SCA',  'Def', 'Tkl',  'Sh',
    'Int', 'Clr', 'Err', 'Succ', 'PrgDist', 'Mis', 'Recov', 'Won%', 'Values'
]

# Select columns
valid_columns = [col for col in selected_columns if col in final_df.columns]
if len(valid_columns) < len(selected_columns):
    missing_columns = set(selected_columns) - set(valid_columns)
    print(f"Warning: The following columns were not found in the DataFrame and were not selected: {missing_columns}")

selected_df = final_df[valid_columns].copy()

print(selected_df)

NameError: name 'final_df' is not defined

In [22]:
# Rename column values to human understandable language : D
selected_df.rename(columns={"Pos": "Position", "Squad": "Team", "Gls":"Goals",
                            "Cmp%":"Pass Cmp%", "TB":"Through Balls",
                             "Sw":"Switch Passes", "Crs":"Crosses",
                            "SCA":"Shot Creating Actions", "Def":"Def Action to Shot", "Tkl":"Tackles",
                             "Sh":"Shots Blocked", "Int":"Interceptions", "Clr":"Clearances",
                            "Err":"Errors", "Succ":"Dribbles Successful", "PrgDist":"Dribble Distance", "Mis":"Mistakes",
                            "Recov":"Ball Recoveries", "Won%":"Air Duels Won%",}, inplace=True)
selected_df.columns

Index(['Player', 'Position', 'Team', 'Comp', 'Age', 'MP', 'Min', 'Goals',
       'Ast', 'G+A', 'xG', 'xA', 'SoT%', 'npxG/Sh', 'G-xG', 'Pass Cmp%',
       'Through Balls', 'Switch Passes', 'Crosses', 'Shot Creating Actions',
       'Def Action to Shot', 'Tackles', 'Shots Blocked', 'Interceptions',
       'Clearances', 'Errors', 'Dribbles Successful', 'Dribble Distance',
       'Mistakes', 'Ball Recoveries', 'Air Duels Won%', 'Values'],
      dtype='str')

In [1]:
# save csv yay
selected_df.to_csv("Final_Dataset.csv")

NameError: name 'selected_df' is not defined